# Forwarding puertos 80 (HTTP) y 443 (HTTPS)
Listen 80
Listen 443

# Módulo básico servidor Apache
LoadModule authz_core_module modules/mod_authz_core.so 
LoadModule ssl_module modules/mod_ssl.so
DocumentRoot c:/xampp/htdocs

# Verificación mediante protocolo SSL con certificado
<VirtualHost _default_:443>
SSLEngine On
SSLCACertificateFile c:/Users/ssr/Documents/certificado-practica2.crt
SSLCertificateFile c:/Users/ssr/Documents/192.168.56.10.crt
SSLCertificateKeyFile c:/Users/ssr/Documents/ClaveServidor 
SSLVerifyClient require
</VirtualHost>

# Redireccionamiento permanente a HTTPS del tráfico HTTP LoadModule alias_module modules/mod_alias.so
<VirtualHost 192.168.56.10:80>
ServerName localhost:80
Redirect permanent / https://192.168.56.10:443/
</VirtualHost>

# Carga del módulo de autenticación
LoadModule auth_basic_module modules/mod_auth_basic.so 
LoadModule authz_host_module modules/mod_authz_host.so 
LoadModule authz_user_module modules/mod_authz_user.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authn_file_module modules/mod_authn_file.so

# Se requieren los 4 usuarios del grupo y que su conexión sea desde la máquina 192.168.56.20
<Directory "c:/xampp/htdocs">
AuthName "Servidor SSR"
AuthType Basic
AuthBasicProvider file
AuthUserFile c:/certificates/users 
<RequireAll>
Require user ANM JFS TOA VBT
Require ip 192.168.56.20
</RequireAll>
</Directory>
